/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Email;

import Employeepanales.*;
import companymanagement.Support;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.RadioButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author home
 */
public class AllEmail extends javax.swing.JPanel {
 public int getI() {
        return i;
    }

    /**
     * @param i the i to set
     */
    public void setI(int i) {
        this.i = i;
    }
   private int i =0;
    /**
     * Creates new form AddEmployee
     */
   
   
   
    public AllEmail() {
        initComponents();
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        p22 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        emailtable = new javax.swing.JTable();

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setText("All Employees");

        setLayout(new java.awt.BorderLayout());

        p22.setBackground(new java.awt.Color(255, 255, 255));
        p22.setLayout(new javax.swing.OverlayLayout(p22));

        emailtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "to", "cc", "subject", "message", "date"
            }
        ));
        jScrollPane3.setViewportView(emailtable);

        p22.add(jScrollPane3);

        add(p22, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable emailtable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel p22;
    // End of variables declaration//GEN-END:variables
}
