/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employeepanales;

import companymanagement.Support;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.RadioButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author home
 */
public class AllEmployees extends javax.swing.JPanel {
 public int getI() {
        return i;
    }

    /**
     * @param i the i to set
     */
    public void setI(int i) {
        this.i = i;
    }
   private int i =0;
    /**
     * Creates new form AddEmployee
     */
   
   
   
    public AllEmployees() {
        initComponents();
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        allEmployeestable = new javax.swing.JTable();

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setText("All Employees");

        setLayout(new java.awt.BorderLayout());

        p1.setBackground(new java.awt.Color(255, 255, 255));
        p1.setLayout(new javax.swing.OverlayLayout(p1));

        allEmployeestable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "employee_id", "first_name", "last_name", "salary", "department_name", "manager_id", "hire_date", "gender", "Email"
            }
        ));
        jScrollPane3.setViewportView(allEmployeestable);

        p1.add(jScrollPane3);

        add(p1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable allEmployeestable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel p1;
    // End of variables declaration//GEN-END:variables
}
