/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employeepanales;

import companymanagement.Support;
import static companymanagement.Support.rs;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.RadioButton;
import javafx.stage.FileChooser;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author home
 */
public class UpdateEmployee extends javax.swing.JPanel {
    String img2 ,f,l,h=null;
    String gender = null;
ImageIcon icon2 = null;
Image dimg = null;
ImageIcon imageIcon = null;
int id, s, m ;

public  void clearance(){
    employee_id.setText(null);
    first_name.setText(null);
    last_name.setText(null);
    salary.setText(null);
    manager_id.setText(null);
    email.setText(null);
    hire_date.setText(null);
    imgtxt.setText(null);  
    e_male.setSelected(false);
    e_female.setSelected(false);
updateimg.setIcon(null);
    }

    public static String getText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
 public int getI() {
        return i;
    }

    /**
     * @param i the i to set
     */
    public void setI(int i) {
        this.i = i;
    }
   private int i =0;
    /**
     * Creates new form AddEmployee
     */
    public UpdateEmployee() {
        
               
        initComponents();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        employee_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        manager_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        e_male = new javax.swing.JRadioButton();
        e_female = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        department = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        imgtxt = new javax.swing.JTextField();
        updateimg = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        hire_date = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setText("Update/Delete Employee");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Employee ID");

        employee_id.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("First Name");

        first_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_nameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Last Name");

        last_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_nameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Salary");

        salary.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Hire Date");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Manager ID");

        manager_id.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Gender");

        e_male.setText("Male");
        e_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_maleActionPerformed(evt);
            }
        });

        e_female.setText("Female");
        e_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_femaleActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Department");

        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Executive", "Sales", "Customer Support", "Hardware Development",
            "Software Development" ,"Marketing","Finance","Legal" ,"Maintenance"}));
department.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        departmentActionPerformed(evt);
    }
    });

    jButton1.setBackground(new java.awt.Color(255, 51, 0));
    jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    jButton1.setForeground(new java.awt.Color(51, 51, 51));
    jButton1.setText("Delete");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton2.setBackground(new java.awt.Color(255, 204, 0));
    jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    jButton2.setForeground(new java.awt.Color(51, 51, 51));
    jButton2.setText("Update");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    jButton3.setBackground(new java.awt.Color(0, 204, 0));
    jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    jButton3.setForeground(new java.awt.Color(255, 255, 255));
    jButton3.setText("Search");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel10.setText("Image");

    imgtxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

    updateimg.setText("Employee Photo");
    updateimg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

    jButton5.setBackground(new java.awt.Color(255, 153, 255));
    jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
    jButton5.setText("Upload");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel11.setText("Email");

    email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    email.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            emailActionPerformed(evt);
        }
    });

    hire_date.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    hire_date.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            hire_dateActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addGap(99, 99, 99)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(employee_id, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jButton3))
                        .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(e_male)
                            .addGap(116, 116, 116)
                            .addComponent(e_female))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(imgtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jButton5)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(manager_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(96, 96, 96)
                            .addComponent(jLabel7)
                            .addGap(99, 99, 99)
                            .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(hire_date, javax.swing.GroupLayout.Alignment.LEADING))))
                .addComponent(updateimg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(42, 42, 42))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel6)
                .addComponent(jLabel11))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel2)
                .addContainerGap(364, Short.MAX_VALUE)))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(updateimg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(employee_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton3))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(22, 22, 22)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(hire_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(manager_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7)
                .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(e_male)
                .addComponent(e_female))
            .addGap(21, 21, 21)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(imgtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton5))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jButton2))
            .addGap(18, 18, 18))
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(484, Short.MAX_VALUE)))
    );

    add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_nameActionPerformed

    private void e_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_maleActionPerformed
        // TODO add your handling code here:
          if(e_male.isSelected()){
              gender = "Male";
              e_female.setSelected(false);
          }
    }//GEN-LAST:event_e_maleActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
        String selecteddepartment = (String) department.getSelectedItem();

        if (selecteddepartment .equals("Executive")) {
            setI(1);
        }
        else if (selecteddepartment .equals("Sales")) {
            setI(2);
        }
        else if (selecteddepartment .equals("Customer Support")) {
            setI(3);
        }
        else if (selecteddepartment .equals("Hardware Development")) {
            setI(4);
        }
        else if (selecteddepartment .equals("Software Development")) {
            setI(5);
        }
        else if (selecteddepartment .equals("Marketing")) {
            setI(6);
        }
        else if (selecteddepartment .equals("Finance")) {
            setI(7);
        }
        else if (selecteddepartment .equals("Legal")) {
            setI(8);
        }
        else
        {
            setI(9);
        }

    }//GEN-LAST:event_departmentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        id =Integer.parseInt(employee_id.getText());
        
     Support.delete(id );
     clearance();
        //Support.dml("delete from employee where employee_id = "+Integer.parseInt(employee_id.getText()) );
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
         // TODO add your handling code here:
           /*id =Integer.parseInt(employee_id.getText());
          f = first_name.getText();
          l = last_name.getText();
          s =  Integer.parseInt(salary.getText());
          m = Integer.parseInt(manager_id.getText() );
          h =  hire_date.getText();
         
        Support.dml("update employee set  first_name =  " + first_name.getText() + 
                 " , "+ "last_name =  "  + last_name.getText() + " , salary =  " +Integer.parseInt(salary.getText()) 
                 + " , hire_date =  " +hire_date.getText() +" , manager_id =  " +Integer.parseInt(manager_id.getText())+
                 " , department_id =  " +getI() +               
                 " where employee_id = "+ Integer.parseInt( employee_id.getText()));
        
         //Date date2 =(Date) new SimpleDateFormat("dd/MM/yyyy").parse(hire_date.getText());  
         
         //Support.dml("update employee set  employee_id =  " + Integer.parseInt( employee_id.getText())+ " where employee_id = "+ Integer.parseInt( employee_id.getText()));
         Support.dml("update employee set  first_name =  " + first_name.getText() + " where employee_id = "+ employee_id.getText());
         Support.dml("update employee set  last_name =  " + last_name.getText() + " where employee_id = "+  employee_id.getText());
         Support.dml("update employee set  salary =  " +salary.getText() + " where employee_id = "+  employee_id.getText());
         Support.dml("update employee set  hire_date =  " + hire_date.getText() + " where employee_id = "+ employee_id.getText());
         Support.dml("update employee set  manager_id =  " +manager_id.getText() + " where employee_id = "+  employee_id.getText());
         Support.dml("update employee set  department_id =  " +getI()+ " where employee_id = "+ employee_id.getText());*/
       
// SimpleDateFormat sdf =  new SimpleDateFormat("dd/MM/YYYY");
        
Support.update(Integer.parseInt(employee_id.getText()),first_name.getText() , last_name.getText(),
                 Integer.parseInt(salary.getText())  , getI(), Integer.parseInt(manager_id.getText() ),
                 hire_date.getText(),gender,imgtxt.getText());
         clearance();
         
  

        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
     try {
         // TODO add your handling code here:
        
         Support.ex("select employee_id, first_name, last_name, salary ,department_id, manager_id, hire_date,gender,img,email from employee where employee_id = " + Integer.parseInt(employee_id.getText()));
        if(rs.isClosed()){
            clearance();
            JOptionPane.showMessageDialog(null,"employee id "+ employee_id.getText()+" is not found !!!");
        }
        else{
         first_name.setText(rs.getString(2));
          email.setText(rs.getString(10));
         last_name.setText(rs.getString(3));
            salary.setText(rs.getString(4));
            setI(Integer.parseInt(rs.getString(5)));
            manager_id.setText(rs.getString(6));
          hire_date.setText(rs.getString(7));
         gender = rs.getString(8);
       if(gender.equals("Male")){
           e_male.setSelected(true);
       e_female.setSelected(false);}
           else if (gender.equals("Female")){
                  e_female.setSelected(true);
                  e_male.setSelected(false);
                   }
           else{
               e_male.setSelected(false);
                e_female.setSelected(false);
           }
        BufferedImage img = null;
         
        if(rs.getString(9).isEmpty()){
                updateimg.setText("No Image");
                            updateimg.setIcon(null);

        /*try {
                img = ImageIO.read(new File(img2));
            } catch (IOException e) {
                e.printStackTrace();
            }
            Image dimg = img.getScaledInstance(updateimg.getWidth(), updateimg.getHeight(),
                Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(dimg);
            updateimg.setIcon(imageIcon);
            imgtxt.setText(img2);*/}
        else{
         img2 =rs.getString(9);
         try {
                img = ImageIO.read(new File(img2));
            } catch (IOException e) {
                e.printStackTrace();
            }
            Image dimg = img.getScaledInstance(updateimg.getWidth(), updateimg.getHeight(),
                Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(dimg);
            updateimg.setIcon(imageIcon);
            imgtxt.setText(img2);
        }}                                                           
        /* first_name.setText(Support.ex("select employee_id, first_name, last_name, salary ,department_id, manager_id, hire_date from employee where employee_id = " + employee_id.getText()).getString(2));
         last_name.setText(Support.ex("select employee_id, first_name, last_name, salary ,department_id, manager_id, hire_date from employee where employee_id = " + employee_id.getText()).getString(3));
         salary.setText(Support.ex("select employee_id, first_name, last_name, salary ,department_id, manager_id, hire_date from employee where employee_id = " + employee_id.getText()).getString(4));
         hire_date.setText(Support.ex("select employee_id, first_name, last_name, salary ,department_id, manager_id, hire_date from employee where employee_id = " + employee_id.getText()).getString(7));
         manager_id.setText(Support.ex("select employee_id, first_name, last_name, salary ,department_id, manager_id, hire_date from employee where employee_id = " + employee_id.getText()).getString(6));
         // first_name.setText(Support.ex("select first_name from employee where id =" + employee_id.getText()));
        setI(Integer.parseInt(Support.ex("select employee_id, first_name, last_name, salary ,department_id, manager_id, hire_date from employee where employee_id = " + employee_id.getText()).getString(5)));
        */
         String selecteddepartment = (String) department.getSelectedItem();
        if (getI()==1) {
            department.setSelectedItem("Executive");
        }
        else if (getI()==2) {
            department.setSelectedItem("Sales");
        }
        else if (getI()==3) {
            department.setSelectedItem("Customer Support");
        }
        else if (getI()==4) {
            department.setSelectedItem("Hardware Development");
        }
        else if (getI()==5) {
           department.setSelectedItem("Software Development");
        }
        else if (getI()==6) {
          department.setSelectedItem("Marketing");
        }
        else if (getI()==7) {
           department.setSelectedItem("Finance");
        }
        else if (getI()==8) {
            department.setSelectedItem("Legal");
        }
        else
        {
            department.setSelectedItem("Maintenance");
        }
        
        
        
       
                
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(UpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);
     }  catch (SQLException ex) {
            Logger.getLogger(UpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
         
      
         
         
         
     
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_nameActionPerformed

    private void e_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_femaleActionPerformed
        // TODO add your handling code here:
           if(e_female.isSelected()){
              gender = "Female";
              e_male.setSelected(false);
          }
    }//GEN-LAST:event_e_femaleActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
  img2 ="D:\\Mohamed\\full stack\\CompanyManagement\\src\\photos\\User_font_awesome.gif";
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        if(f.isFile())
        img2 = f.getAbsolutePath();
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(img2));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(updateimg.getWidth(), updateimg.getHeight(),
            Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        updateimg.setIcon(imageIcon);
        imgtxt.setText(img2);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void hire_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hire_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hire_dateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> department;
    private javax.swing.JRadioButton e_female;
    private javax.swing.JRadioButton e_male;
    private javax.swing.JTextField email;
    private javax.swing.JTextField employee_id;
    private javax.swing.JTextField first_name;
    private javax.swing.JTextField hire_date;
    private javax.swing.JTextField imgtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField last_name;
    private javax.swing.JTextField manager_id;
    private javax.swing.JTextField salary;
    private javax.swing.JLabel updateimg;
    // End of variables declaration//GEN-END:variables
}
