/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import Employeepanales.*;
import companymanagement.Support;
import static companymanagement.Support.rs;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.RadioButton;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author home
 */
public class UpdateCustomer extends javax.swing.JPanel {
    String f, l, e, d = null;
    String gender = null;  
     String imgy = null;
   int a = 0;
   ImageIcon imageIcon =null;
    Image dimg = null;
          int id ;  
 public int getI() {
        return i;
    }
 

 
 public  void clearance(){
     customer_id.setText(null);
     first_name.setText(null);
     last_name.setText(null);
     email.setText(null);
     address.setText(null);
     e_male.setSelected(false);
     e_female.setSelected(false);
     imgtxt.setText(null); 
updateimg.setIcon(null);
    }
    /**
     * @param i the i to set
     */

   private int i =0;
    /**
     * Creates new form AddEmployee
     */
    public UpdateCustomer() {
        initComponents();
        clearance();
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        customer_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        e_male = new javax.swing.JRadioButton();
        e_female = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        imgtxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        updateimg = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Customer id");

        customer_id.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("First Name");

        first_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Last Name");

        last_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_nameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Address");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Gender");

        e_male.setText("Male");
        e_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_maleActionPerformed(evt);
            }
        });

        e_female.setText("Female");
        e_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_femaleActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Image");

        imgtxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 153, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        updateimg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Email");

        address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setText("Update/Delete Employee");

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 204, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateimg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(customer_id, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                                    .addComponent(first_name, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                                    .addComponent(last_name, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(imgtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2))
                                    .addComponent(address)
                                    .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(39, 39, 39)
                                .addComponent(jButton4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(e_male)
                                .addGap(116, 116, 116)
                                .addComponent(e_female))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(46, 46, 46)))
                        .addContainerGap(45, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateimg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customer_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(e_male)
                    .addComponent(e_female))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(imgtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(29, 29, 29))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_nameActionPerformed

    private void e_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_maleActionPerformed
        // TODO add your handling code here:
        if(e_male.isSelected()){
            gender = "Male";
            e_female.setSelected(false);
        }
    }//GEN-LAST:event_e_maleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:               
     
    
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        if(f.isFile())
          imgy = f.getAbsolutePath();
     BufferedImage img = null;
        try {
            img = ImageIO.read(new File(imgy));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(updateimg.getWidth(), updateimg.getHeight(),
                Image.SCALE_SMOOTH);     
        ImageIcon imageIcon = new ImageIcon(dimg);
             updateimg.setIcon(imageIcon);
     imgtxt.setText(imgy);
     
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void e_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_femaleActionPerformed
        // TODO add your handling code here:
         if(e_female.isSelected()){
            gender = "Female";
            e_male.setSelected(false);
        }
    }//GEN-LAST:event_e_femaleActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //id =Integer.parseInt(customer_id.getText());
        //JOptionPane.showConfirmDialog(null, "Are you sure you want to delete "+first_name.getText()+" "+last_name.getText());
        Support.deleteCustomer(Integer.parseInt(customer_id.getText()) );
        clearance();
        //Support.dml("delete from employee where employee_id = "+Integer.parseInt(employee_id.getText()) );

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // TODO add your handling code here:
       /* id =Integer.parseInt(customer_id.getText());
        f = first_name.getText();
        l = last_name.getText();
     d = address.getText();       
        e=  email.getText();*/
        /* Support.dml("update employee set  first_name =  " + first_name.getText() +
            " , "+ "last_name =  "  + last_name.getText() + " , salary =  " +Integer.parseInt(salary.getText())
            + " , hire_date =  " +hire_date.getText() +" , manager_id =  " +Integer.parseInt(manager_id.getText())+
            " , department_id =  " +getI() +
            " where employee_id = "+ Integer.parseInt( employee_id.getText()));

        //Date date2 =(Date) new SimpleDateFormat("dd/MM/yyyy").parse(hire_date.getText());

        //Support.dml("update employee set  employee_id =  " + Integer.parseInt( employee_id.getText())+ " where employee_id = "+ Integer.parseInt( employee_id.getText()));
        Support.dml("update employee set  first_name =  " + first_name.getText() + " where employee_id = "+ employee_id.getText());
        Support.dml("update employee set  last_name =  " + last_name.getText() + " where employee_id = "+  employee_id.getText());
        Support.dml("update employee set  salary =  " +salary.getText() + " where employee_id = "+  employee_id.getText());
        Support.dml("update employee set  hire_date =  " + hire_date.getText() + " where employee_id = "+ employee_id.getText());
        Support.dml("update employee set  manager_id =  " +manager_id.getText() + " where employee_id = "+  employee_id.getText());
        Support.dml("update employee set  department_id =  " +getI()+ " where employee_id = "+ employee_id.getText());*/
        //SimpleDateFormat sdf =  new SimpleDateFormat("dd/MM/YYYY");

        Support.updateCustomer(Integer.parseInt(customer_id.getText()),first_name.getText() ,last_name.getText(),
            address.getText()  , email.getText(),gender,imgtxt.getText());
        clearance();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            // TODO add your handling code here:

            Support.ex("select customer_id, first_name, last_name, address_state ,email_address,gender,img from customer where customer_id = " + Integer.parseInt(customer_id.getText()));
            if(rs.isClosed()){
                clearance();
                JOptionPane.showMessageDialog(null,"employee id "+ customer_id.getText()+" is not found !!!");
            }
            else{
                first_name.setText(rs.getString(2));
                last_name.setText(rs.getString(3));
                address.setText(rs.getString(4));
                email.setText(rs.getString(5));
                gender = rs.getString(6);
                if(gender.equals("Male")){
                    e_male.setSelected(true);}
                else if (gender.equals("Female")){
                    e_female.setSelected(true);
                    e_male.setSelected(false);
                }
                else{
                    e_male.setSelected(true);
                    e_female.setSelected(false);
                }
                BufferedImage img = null;

                if(rs.getString(7).isEmpty()){
                    updateimg.setText("No Image");
                    updateimg.setIcon(null);

                    /*try {
                        img = ImageIO.read(new File(img2));
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    Image dimg = img.getScaledInstance(updateimg.getWidth(), updateimg.getHeight(),
                        Image.SCALE_SMOOTH);
                    ImageIcon imageIcon = new ImageIcon(dimg);
                    updateimg.setIcon(imageIcon);
                    imgtxt.setText(img2);*/}
                else{
                    String imgy = rs.getString(7);
                    try {
                        img = ImageIO.read(new File(imgy));
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    Image dimg = img.getScaledInstance(updateimg.getWidth(), updateimg.getHeight(),
                        Image.SCALE_SMOOTH);
                    ImageIcon imageIcon = new ImageIcon(dimg);
                    updateimg.setIcon(imageIcon);
                    imgtxt.setText(imgy);
                }}
                /* first_name.setText(Support.ex("select employee_id, first_name, last_name, salary ,department_id, manager_id, hire_date from employee where employee_id = " + employee_id.getText()).getString(2));
                last_name.setText(Support.ex("select employee_id, first_name, last_name, salary ,department_id, manager_id, hire_date from employee where employee_id = " + employee_id.getText()).getString(3));
                salary.setText(Support.ex("select employee_id, first_name, last_name, salary ,department_id, manager_id, hire_date from employee where employee_id = " + employee_id.getText()).getString(4));
                hire_date.setText(Support.ex("select employee_id, first_name, last_name, salary ,department_id, manager_id, hire_date from employee where employee_id = " + employee_id.getText()).getString(7));
                manager_id.setText(Support.ex("select employee_id, first_name, last_name, salary ,department_id, manager_id, hire_date from employee where employee_id = " + employee_id.getText()).getString(6));
                // first_name.setText(Support.ex("select first_name from employee where id =" + employee_id.getText()));
                setI(Integer.parseInt(Support.ex("select employee_id, first_name, last_name, salary ,department_id, manager_id, hire_date from employee where employee_id = " + employee_id.getText()).getString(5)));
             */
        } catch (SQLException ex) {
            Logger.getLogger(UpdateCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdateCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField customer_id;
    private javax.swing.JRadioButton e_female;
    private javax.swing.JRadioButton e_male;
    private javax.swing.JTextField email;
    private javax.swing.JTextField first_name;
    private javax.swing.JTextField imgtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField last_name;
    private javax.swing.JLabel updateimg;
    // End of variables declaration//GEN-END:variables
}
